###creating user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "name":"h03an20h",
  "email":"h03an20h@gmail.com",
  "password":"123456",
  "role":"admin"
}
###login
POST http://localhost:5000/api/auth/login
Content-type: application/json 

{
  "email":"h03an20h@gmail.com",
  "password":"123456",
  "role":"admin"
}

###get the item 
GET http://localhost:5000/api/products/6a24193f953e24ca7ea2da9d

###creating new product
POST http://localhost:5000/api/products
Content-Type: application/json

{
  "name": "iPhone 16",
  "description": "Apple flagship phone",
  "category": "Mobiles",
  "price": 89999,
  "stock": 10,
  "image": "iphone16.jpg"
}

###update the product
PUT http://localhost:5000/api/products/6a41c7af1af9d6edfac4aa01
Content-Type: application/json

{
  "price": 84999
}

###add to cart 
POST http://localhost:5000/api/cart/add
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{
  "productId":"PRODUCT_ID",
  "quantity":2
}

###test payment
POST http://localhost:5000/api/payment/create-order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMjQxZWQ2MjUxZDIyMTFmMGM1MDFiMiIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzgwODAxNTM2LCJleHAiOjE3ODA4MDIxMzZ9.eWZ8jBFUx1q-GUYAJE6Jk5YxpbGG7OKpCKrW2zFySOo
Content-Type: application/json

{
  "amount": 1000
}

###order
POST http://localhost:5000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzk1MjNkYTgyMzNjN2VkMDMwYjA4YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4Mjg3MTE0MSwiZXhwIjoxNzgyODcxNzQxfQ.uSuUTLO0uKNYOIpcXVoxpN3AXA8xxW085P12SqPCiIY
Content-Type: application/json

{
  "products": [
    {
      "product": "6872c9b5d3f8f8a8d1234567",
      "quantity": 2
    },
    {
      "product": "6872ca01d3f8f8a8d1234568",
      "quantity": 1
    }
  ],
  "totalAmount": 154999,
  "paymentMethod": "Razorpay",
  "paymentStatus": "Paid",
  "shippingAddress": "Door No. 10-15, Main Road, Kakinada, Andhra Pradesh, India"
}

###my-orders
GET http://localhost:5000/api/orders/my-orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzk1MjNkYTgyMzNjN2VkMDMwYjA4YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4Mjg3MTE0MSwiZXhwIjoxNzgyODcxNzQxfQ.uSuUTLO0uKNYOIpcXVoxpN3AXA8xxW085P12SqPCiIY
Content-Type: application/json

{
  "user":{ "id": "6a39523da8233c7ed030b08c" }
}
###
GET http://localhost:5000/api/orders/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzk1MjNkYTgyMzNjN2VkMDMwYjA4YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4Mjc4NTYxMSwiZXhwIjoxNzgyNzg2MjExfQ.1-5gsGLqNq45Wrer-Vu6i_7dzkvl_4HPSkHYb7K1k1c
Content-Type: application/json

###orderstatus update
PUT http://localhost:5000/api/orders/6a447513b9f5b5b980517a76/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzk1MjNkYTgyMzNjN2VkMDMwYjA4YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4Mjg3MTc0NCwiZXhwIjoxNzgyODczNTQ0fQ._PATyrDbd07TOmJ4huRWkU7ilV_vHBbWPkOSAm6mwL0
Content-Type: application/json

{
  "id":"6a447513b9f5b5b980517a76",
  "orderStatus":"Delivered"
}



### dashboard stats
GET http://localhost:5000/api/dashboard/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhMzk1MjNkYTgyMzNjN2VkMDMwYjA4YyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4Mjk1NjY0MiwiZXhwIjoxNzgyOTU4NDQyfQ.Q_503QbRV5tXsET0YzQMwooOnWJnaq7_uRvE12Ek94c
Content-Type: application/json


### 
GET http://localhost:5000/api/products/related/6a41c7af1af9d6edfac4aa01

###
DELETE http://localhost:5000/api/products/6a5ab8aef3ae1574855b90e9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTc3NTFmOTE3ZDRlNGIyOGM3YjIwNSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4NDMzMDMyOCwiZXhwIjoxNzg0MzMyMTI4fQ.yKIf8YLdQq3yYmdNnBfvVbeOwEQHgz_lb_8IL0XaiHA
###
POST http://localhost:5000/api/auth/register
Content-Type:application/json

{
  "name":"Hemanth",
  "email":"h03an20h@gmail.com",
  "password":"123456",
  "role":"admin"
}

###
GET http://localhost:5000/api/admin/test 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTc3NTFmOTE3ZDRlNGIyOGM3YjIwNSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4NDI1NDcxNCwiZXhwIjoxNzg0MjU2NTE0fQ.XWl0GaD5lj4Ha_k3bVNZJ6r-ul6BBZOoGWsnxtqz52c


###
GET http://localhost:5000/api/auth/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTc3NTFmOTE3ZDRlNGIyOGM3YjIwNSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc4NDUxMDIwMywiZXhwIjoxNzg0NTEyMDAzfQ.U5AVr_mZYx2NAIBvWXoMCfT05BeX7RKhAOAeNlJEfWA
